// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-merchants.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-merchants.ts
var search_merchants_default = defineTool({
  name: "search_merchants",
  title: "Search happy hour spots",
  description: "Search active happy hour bars and restaurants by name, city, state, or neighborhood.",
  inputSchema: {
    query: z.string().trim().min(1).optional().describe("Name text to match, e.g. 'Dai Hachi'."),
    city: z.string().trim().min(1).optional().describe("City name, e.g. 'Brooklyn'."),
    state: z.string().trim().length(2).optional().describe("Two-letter state code, e.g. 'NY'."),
    neighborhood: z.string().trim().min(1).optional().describe("Neighborhood name."),
    limit: z.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, city, state, neighborhood, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let builder = supabase.from("Merchant").select(
      "id, restaurant_name, slug, street_address, city, state, zip_code, neighborhood, phone_number, website, verification_is_verified"
    ).eq("is_active", true).limit(limit ?? 20);
    if (query) builder = builder.ilike("restaurant_name", `%${query}%`);
    if (city) builder = builder.ilike("city", city);
    if (state) builder = builder.ilike("state", state);
    if (neighborhood) builder = builder.ilike("neighborhood", `%${neighborhood}%`);
    const { data, error } = await builder;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { merchants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-merchant.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_merchant_default = defineTool2({
  name: "get_merchant",
  title: "Get merchant details",
  description: "Get one merchant's profile plus its weekly happy hour windows and upcoming events, by id or slug.",
  inputSchema: {
    id: z2.number().int().positive().optional().describe("Numeric merchant id."),
    slug: z2.string().trim().min(1).optional().describe("Merchant slug from its profile URL.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!id && !slug) throw new ToolError("Provide either id or slug.");
    const supabase = supabaseForUser(ctx);
    let merchantQuery = supabase.from("Merchant").select(
      "id, restaurant_name, slug, street_address, street_address_line_2, city, state, zip_code, neighborhood, phone_number, website, logo_url, latitude, longitude, verification_is_verified"
    ).eq("is_active", true).limit(1);
    merchantQuery = id ? merchantQuery.eq("id", id) : merchantQuery.eq("slug", slug);
    const { data: merchants, error } = await merchantQuery;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const merchant = merchants?.[0];
    if (!merchant) return { content: [{ type: "text", text: "Merchant not found" }], isError: true };
    const [{ data: happyHours }, { data: events }] = await Promise.all([
      supabase.from("merchant_happy_hour").select("day_of_week, happy_hour_start, happy_hour_end").eq("store_id", merchant.id).order("day_of_week"),
      supabase.from("merchant_events").select(
        "id, title, description, event_type, category_tags, event_date, start_time, end_time, recurrence_rule, recurrence_day"
      ).eq("restaurant_id", merchant.id).eq("is_active", true).limit(25)
    ]);
    const result = {
      merchant,
      happy_hours: happyHours ?? [],
      events: events ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/search-events.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var search_events_default = defineTool3({
  name: "search_events",
  title: "Search events",
  description: "Search active bar and restaurant events (trivia, DJ, live music, etc.) by city, neighborhood, category tag, or weekday.",
  inputSchema: {
    city: z3.string().trim().min(1).optional().describe("City name, e.g. 'Brooklyn'."),
    neighborhood: z3.string().trim().min(1).optional(),
    category_tag: z3.string().trim().min(1).optional().describe("Category tag such as 'trivia', 'dj', or 'live-music'."),
    day_of_week: z3.number().int().min(0).max(6).optional().describe("Recurring weekday, 0 = Sunday through 6 = Saturday."),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, neighborhood, category_tag, day_of_week, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let builder = supabase.from("merchant_events").select(
      "id, restaurant_id, title, description, event_type, category_tags, city, neighborhood, event_date, start_time, end_time, recurrence_rule, recurrence_day"
    ).eq("is_active", true).limit(limit ?? 20);
    if (city) builder = builder.ilike("city", city);
    if (neighborhood) builder = builder.ilike("neighborhood", `%${neighborhood}%`);
    if (category_tag) builder = builder.contains("category_tags", [category_tag]);
    if (day_of_week !== void 0) builder = builder.eq("recurrence_day", day_of_week);
    const { data, error } = await builder;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-favorites.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_favorites_default = defineTool4({
  name: "list_favorites",
  title: "List my favorites",
  description: "List the merchants the signed-in user has saved as favorites.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("favorites").select("merchant_id, created_at, Merchant(id, restaurant_name, slug, city, state, neighborhood)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { favorites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-favorite.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var add_favorite_default = defineTool5({
  name: "add_favorite",
  title: "Save a favorite",
  description: "Save a merchant to the signed-in user's favorites.",
  inputSchema: {
    merchant_id: z4.number().int().positive().describe("Numeric merchant id to save.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ merchant_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("favorites").insert({ user_id: ctx.getUserId(), merchant_id }).select("id, merchant_id").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { favorite: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gohcqazhofdhkghfxfok";
var mcp_default = defineMcp({
  name: "sipmunchyap",
  title: "sipmunchyap",
  version: "0.1.0",
  instructions: "Tools for SipMunchYap, a happy hour and events discovery app. Use `search_merchants` to find bars and restaurants, `get_merchant` for one spot's happy hour windows and events, `search_events` for trivia/DJ/live-music events, and `list_favorites` / `add_favorite` to read and update the signed-in user's saved spots.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_merchants_default,
    get_merchant_default,
    search_events_default,
    list_favorites_default,
    add_favorite_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
